spring:
  application:
    name: jium

  datasource:
    # MariaDB ë“œë¼ì´ë²„ í´ë˜ìŠ¤ ì´ë¦„
    driver-class-name: org.mariadb.jdbc.Driver 
    # ì ‘ì†í•  DB ì„œë²„ ì£¼ì†Œ (localhostì˜ 3306 í¬íŠ¸ì— ìˆëŠ” jium ë°ì´í„°ë² ì´ìŠ¤)
    url: jdbc:mariadb://localhost:3306/jium 
    # DB ì ‘ì† ê³„ì •
    username: root # ğŸ‘ˆ ë³¸ì¸ì˜ DB ê³„ì •ìœ¼ë¡œ ë³€ê²½
    # DB ì ‘ì† ë¹„ë°€ë²ˆí˜¸
    password: 971024 # ğŸ‘ˆ ë³¸ì¸ì˜ DB ë¹„ë°€ë²ˆí˜¸ë¡œ ë³€ê²½